export const WORLD_COUNTRIES = [
  { name: 'أفغانستان', code: 'AF', flag: '🇦🇫' },
  { name: 'ألبانيا', code: 'AL', flag: '🇦🇱' },
  { name: 'الجزائر', code: 'DZ', flag: '🇩🇿' },
  { name: 'أندورا', code: 'AD', flag: '🇦🇩' },
  { name: 'أنغولا', code: 'AO', flag: '🇦🇴' },
  { name: 'أنتيغوا وبربودا', code: 'AG', flag: '🇦🇬' },
  { name: 'الأرجنتين', code: 'AR', flag: '🇦🇷' },
  { name: 'أرمينيا', code: 'AM', flag: '🇦🇲' },
  { name: 'أستراليا', code: 'AU', flag: '🇦🇺' },
  { name: 'النمسا', code: 'AT', flag: '🇦🇹' },
  { name: 'أذربيجان', code: 'AZ', flag: '🇦🇿' },
  { name: 'جزر البهاما', code: 'BS', flag: '🇧🇸' },
  { name: 'البحرين', code: 'BH', flag: '🇧🇭' },
  { name: 'بنغلاديش', code: 'BD', flag: '🇧🇩' },
  { name: 'باربادوس', code: 'BB', flag: '🇧🇧' },
  { name: 'بيلاروسيا', code: 'BY', flag: '🇧🇾' },
  { name: 'بلجيكا', code: 'BE', flag: '🇧🇪' },
  { name: 'بليز', code: 'BZ', flag: '🇧🇿' },
  { name: 'بنين', code: 'BJ', flag: '🇧🇯' },
  { name: 'بوتان', code: 'BT', flag: '🇧🇹' },
  { name: 'بوليفيا', code: 'BO', flag: '🇧🇴' },
  { name: 'البوسنة والهرسك', code: 'BA', flag: '🇧🇦' },
  { name: 'بوتسوانا', code: 'BW', flag: '🇧🇼' },
  { name: 'البرازيل', code: 'BR', flag: '🇧🇷' },
  { name: 'بروناي', code: 'BN', flag: '🇧🇳' },
  { name: 'بلغاريا', code: 'BG', flag: '🇧🇬' },
  { name: 'بوركينا فاسو', code: 'BF', flag: '🇧🇫' },
  { name: 'بوروندي', code: 'BI', flag: '🇧🇮' },
  { name: 'كابو فيردي', code: 'CV', flag: '🇨🇻' },
  { name: 'كمبوديا', code: 'KH', flag: '🇰🇭' },
  { name: 'الكاميرون', code: 'CM', flag: '🇨🇲' },
  { name: 'كندا', code: 'CA', flag: '🇨🇦' },
  { name: 'جمهورية أفريقيا الوسطى', code: 'CF', flag: '🇨🇫' },
  { name: 'تشاد', code: 'TD', flag: '🇹🇩' },
  { name: 'تشيلي', code: 'CL', flag: '🇨🇱' },
  { name: 'الصين', code: 'CN', flag: '🇨🇳' },
  { name: 'كولومبيا', code: 'CO', flag: '🇨🇴' },
  { name: 'جزر القمر', code: 'KM', flag: '🇰🇲' },
  { name: 'الكونغو', code: 'CG', flag: '🇨🇬' },
  { name: 'كوستاريكا', code: 'CR', flag: '🇨🇷' },
  { name: 'كرواتيا', code: 'HR', flag: '🇭🇷' },
  { name: 'كوبا', code: 'CU', flag: '🇨🇺' },
  { name: 'قبرص', code: 'CY', flag: '🇨🇾' },
  { name: 'التشيك', code: 'CZ', flag: '🇨🇿' },
  { name: 'الدنمارك', code: 'DK', flag: '🇩🇰' },
  { name: 'جيبوتي', code: 'DJ', flag: '🇩🇯' },
  { name: 'دومينيكا', code: 'DM', flag: '🇩🇲' },
  { name: 'جمهورية الدومينيكان', code: 'DO', flag: '🇩🇴' },
  { name: 'الإكوادور', code: 'EC', flag: '🇪🇨' },
  { name: 'مصر', code: 'EG', flag: '🇪🇬' },
  { name: 'السلفادور', code: 'SV', flag: '🇸🇻' },
  { name: 'غينيا الاستوائية', code: 'GQ', flag: '🇬🇶' },
  { name: 'إريتريا', code: 'ER', flag: '🇪🇷' },
  { name: 'إستونيا', code: 'EE', flag: '🇪🇪' },
  { name: 'إسواتيني', code: 'SZ', flag: '🇸🇿' },
  { name: 'إثيوبيا', code: 'ET', flag: '🇪🇹' },
  { name: 'فيجي', code: 'FJ', flag: '🇫🇯' },
  { name: 'فنلندا', code: 'FI', flag: '🇫🇮' },
  { name: 'فرنسا', code: 'FR', flag: '🇫🇷' },
  { name: 'الغابون', code: 'GA', flag: '🇬🇦' },
  { name: 'غامبيا', code: 'GM', flag: '🇬🇲' },
  { name: 'جورجيا', code: 'GE', flag: '🇬🇪' },
  { name: 'ألمانيا', code: 'DE', flag: '🇩🇪' },
  { name: 'غانا', code: 'GH', flag: '🇬🇭' },
  { name: 'اليونان', code: 'GR', flag: '🇬🇷' },
  { name: 'غرينادا', code: 'GD', flag: '🇬🇩' },
  { name: 'غواتيمالا', code: 'GT', flag: '🇬🇹' },
  { name: 'غينيا', code: 'GN', flag: '🇬🇳' },
  { name: 'غينيا بيساو', code: 'GW', flag: '🇬🇼' },
  { name: 'غويانا', code: 'GY', flag: '🇬🇾' },
  { name: 'هايتي', code: 'HT', flag: '🇭🇹' },
  { name: 'هندوراس', code: 'HN', flag: '🇭🇳' },
  { name: 'المجر', code: 'HU', flag: '🇭🇺' },
  { name: 'آيسلندا', code: 'IS', flag: '🇮🇸' },
  { name: 'الهند', code: 'IN', flag: '🇮🇳' },
  { name: 'إندونيسيا', code: 'ID', flag: '🇮🇩' },
  { name: 'إيران', code: 'IR', flag: '🇮🇷' },
  { name: 'العراق', code: 'IQ', flag: '🇮🇶' },
  { name: 'أيرلندا', code: 'IE', flag: '🇮🇪' },
  { name: 'إسرائيل', code: 'IL', flag: '🇮🇱' },
  { name: 'إيطاليا', code: 'IT', flag: '🇮🇹' },
  { name: 'جامايكا', code: 'JM', flag: '🇯🇲' },
  { name: 'اليابان', code: 'JP', flag: '🇯🇵' },
  { name: 'الأردن', code: 'JO', flag: '🇯🇴' },
  { name: 'كازاخستان', code: 'KZ', flag: '🇰🇿' },
  { name: 'كينيا', code: 'KE', flag: '🇰🇪' },
  { name: 'كيريباتي', code: 'KI', flag: '🇰🇮' },
  { name: 'كوريا الشمالية', code: 'KP', flag: '🇰🇵' },
  { name: 'كوريا الجنوبية', code: 'KR', flag: '🇰🇷' },
  { name: 'الكويت', code: 'KW', flag: '🇰🇼' },
  { name: 'قرغيزستان', code: 'KG', flag: '🇰🇬' },
  { name: 'لاوس', code: 'LA', flag: '🇱🇦' },
  { name: 'لاتفيا', code: 'LV', flag: '🇱🇻' },
  { name: 'لبنان', code: 'LB', flag: '🇱🇧' },
  { name: 'ليسوتو', code: 'LS', flag: '🇱🇸' },
  { name: 'ليبيريا', code: 'LR', flag: '🇱🇷' },
  { name: 'ليبيا', code: 'LY', flag: '🇱🇾' },
  { name: 'ليختنشتاين', code: 'LI', flag: '🇱🇮' },
  { name: 'ليتوانيا', code: 'LT', flag: '🇱🇹' },
  { name: 'لوكسمبورغ', code: 'LU', flag: '🇱🇺' },
  { name: 'مدغشقر', code: 'MG', flag: '🇲🇬' },
  { name: 'مالاوي', code: 'MW', flag: '🇲🇼' },
  { name: 'ماليزيا', code: 'MY', flag: '🇲🇾' },
  { name: 'المالديف', code: 'MV', flag: '🇲🇻' },
  { name: 'مالي', code: 'ML', flag: '🇲🇱' },
  { name: 'مالطا', code: 'MT', flag: '🇲🇹' },
  { name: 'جزر مارشال', code: 'MH', flag: '🇲🇭' },
  { name: 'موريتانيا', code: 'MR', flag: '🇲🇷' },
  { name: 'موريشيوس', code: 'MU', flag: '🇲🇺' },
  { name: 'المكسيك', code: 'MX', flag: '🇲🇽' },
  { name: 'ميكرونيزيا', code: 'FM', flag: '🇫🇲' },
  { name: 'مولدوفا', code: 'MD', flag: '🇲🇩' },
  { name: 'موناكو', code: 'MC', flag: '🇲🇨' },
  { name: 'منغوليا', code: 'MN', flag: '🇲🇳' },
  { name: 'الجبل الأسود', code: 'ME', flag: '🇲🇪' },
  { name: 'المغرب', code: 'MA', flag: '🇲🇦' },
  { name: 'موزمبيق', code: 'MZ', flag: '🇲🇿' },
  { name: 'ميانمار', code: 'MM', flag: '🇲🇲' },
  { name: 'ناميبيا', code: 'NA', flag: '🇳🇦' },
  { name: 'ناورو', code: 'NR', flag: '🇳🇷' },
  { name: 'نيبال', code: 'NP', flag: '🇳🇵' },
  { name: 'هولندا', code: 'NL', flag: '🇳🇱' },
  { name: 'نيوزيلندا', code: 'NZ', flag: '🇳🇿' },
  { name: 'نيكاراغوا', code: 'NI', flag: '🇳🇮' },
  { name: 'النيجر', code: 'NE', flag: '🇳🇪' },
  { name: 'نيجيريا', code: 'NG', flag: '🇳🇬' },
  { name: 'مقدونيا الشمالية', code: 'MK', flag: '🇲🇰' },
  { name: 'النرويج', code: 'NO', flag: '🇳🇴' },
  { name: 'عمان', code: 'OM', flag: '🇴🇲' },
  { name: 'باكستان', code: 'PK', flag: '🇵🇰' },
  { name: 'بالاو', code: 'PW', flag: '🇵🇼' },
  { name: 'فلسطين', code: 'PS', flag: '🇵🇸' },
  { name: 'بنما', code: 'PA', flag: '🇵🇦' },
  { name: 'بابوا غينيا الجديدة', code: 'PG', flag: '🇵🇬' },
  { name: 'باراغواي', code: 'PY', flag: '🇵🇾' },
  { name: 'بيرو', code: 'PE', flag: '🇵🇪' },
  { name: 'الفلبين', code: 'PH', flag: '🇵🇭' },
  { name: 'بولندا', code: 'PL', flag: '🇵🇱' },
  { name: 'البرتغال', code: 'PT', flag: '🇵🇹' },
  { name: 'قطر', code: 'QA', flag: '🇶🇦' },
  { name: 'رومانيا', code: 'RO', flag: '🇷🇴' },
  { name: 'روسيا', code: 'RU', flag: '🇷🇺' },
  { name: 'رواندا', code: 'RW', flag: '🇷🇼' },
  { name: 'سانت كيتس ونيفيس', code: 'KN', flag: '🇰🇳' },
  { name: 'سانت لوسيا', code: 'LC', flag: '🇱🇨' },
  { name: 'سانت فينسنت والغرينادين', code: 'VC', flag: '🇻🇨' },
  { name: 'ساموا', code: 'WS', flag: '🇼🇸' },
  { name: 'سان مارينو', code: 'SM', flag: '🇸🇲' },
  { name: 'ساو تومي وبرينسيب', code: 'ST', flag: '🇸🇹' },
  { name: 'السعودية', code: 'SA', flag: '🇸🇦' },
  { name: 'السنغال', code: 'SN', flag: '🇸🇳' },
  { name: 'صربيا', code: 'RS', flag: '🇷🇸' },
  { name: 'سيشل', code: 'SC', flag: '🇸🇨' },
  { name: 'سيراليون', code: 'SL', flag: '🇸🇱' },
  { name: 'سنغافورة', code: 'SG', flag: '🇸🇬' },
  { name: 'سلوفاكيا', code: 'SK', flag: '🇸🇰' },
  { name: 'سلوفينيا', code: 'SI', flag: '🇸🇮' },
  { name: 'جزر سليمان', code: 'SB', flag: '🇸🇧' },
  { name: 'الصومال', code: 'SO', flag: '🇸🇴' },
  { name: 'جنوب أفريقيا', code: 'ZA', flag: '🇿🇦' },
  { name: 'جنوب السودان', code: 'SS', flag: '🇸🇸' },
  { name: 'إسبانيا', code: 'ES', flag: '🇪🇸' },
  { name: 'سريلانكا', code: 'LK', flag: '🇱🇰' },
  { name: 'السودان', code: 'SD', flag: '🇸🇩' },
  { name: 'سورينام', code: 'SR', flag: '🇸🇷' },
  { name: 'السويد', code: 'SE', flag: '🇸🇪' },
  { name: 'سويسرا', code: 'CH', flag: '🇨🇭' },
  { name: 'سوريا', code: 'SY', flag: '🇸🇾' },
  { name: 'طاجيكستان', code: 'TJ', flag: '🇹🇯' },
  { name: 'تنزانيا', code: 'TZ', flag: '🇹🇿' },
  { name: 'تايلاند', code: 'TH', flag: '🇹🇭' },
  { name: 'تيمور الشرقية', code: 'TL', flag: '🇹🇱' },
  { name: 'توغو', code: 'TG', flag: '🇹🇬' },
  { name: 'تونغا', code: 'TO', flag: '🇹🇴' },
  { name: 'ترينيداد وتوباغو', code: 'TT', flag: '🇹🇹' },
  { name: 'تونس', code: 'TN', flag: '🇹🇳' },
  { name: 'تركيا', code: 'TR', flag: '🇹🇷' },
  { name: 'تركمانستان', code: 'TM', flag: '🇹🇲' },
  { name: 'توفالو', code: 'TV', flag: '🇹🇻' },
  { name: 'أوغندا', code: 'UG', flag: '🇺🇬' },
  { name: 'أوكرانيا', code: 'UA', flag: '🇺🇦' },
  { name: 'الإمارات', code: 'AE', flag: '🇦🇪' },
  { name: 'المملكة المتحدة', code: 'GB', flag: '🇬🇧' },
  { name: 'الولايات المتحدة', code: 'US', flag: '🇺🇸' },
  { name: 'الأوروغواي', code: 'UY', flag: '🇺🇾' },
  { name: 'أوزبكستان', code: 'UZ', flag: '🇺🇿' },
  { name: 'فانواتو', code: 'VU', flag: '🇻🇺' },
  { name: 'الفاتيكان', code: 'VA', flag: '🇻🇦' },
  { name: 'فنزويلا', code: 'VE', flag: '🇻🇪' },
  { name: 'فيتنام', code: 'VN', flag: '🇻🇳' },
  { name: 'اليمن', code: 'YE', flag: '🇾🇪' },
  { name: 'زامبيا', code: 'ZM', flag: '🇿🇲' },
  { name: 'زيمبابوي', code: 'ZW', flag: '🇿🇼' }
];
